# Generated by Django 2.1.2 on 2018-10-21 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='data',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
