# Generated by Django 2.1.2 on 2018-10-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0002_auto_20181021_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='sended',
        ),
        migrations.AddField(
            model_name='change',
            name='send',
            field=models.BooleanField(default=False, editable=False, verbose_name='Wysłana'),
        ),
    ]
