# Generated by Django 2.1.2 on 2018-10-26 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=6, unique_for_year=True, verbose_name='numer')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='data')),
                ('sellings', models.SmallIntegerField(default=20, verbose_name='ilość sprzedaży')),
            ],
        ),
    ]
