# Generated by Django 2.1.2 on 2018-10-26 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20181026_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data'),
        ),
    ]
