# Generated by Django 2.1.2 on 2018-10-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20181026_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='big_changes',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='data',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='sellings',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='small_changes',
        ),
    ]
