# Generated by Django 2.1.2 on 2018-10-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20181026_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.IntegerField(verbose_name='numer'),
        ),
    ]
