# Generated by Django 2.1.2 on 2018-10-26 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_auto_20181026_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data'),
        ),
    ]
