# Generated by Django 2.1.2 on 2018-10-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_bill_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='big_changes',
            field=models.SmallIntegerField(default=30, verbose_name='ilość dużych zmian'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sellings',
            field=models.SmallIntegerField(default=20, verbose_name='ilość sprzedaży'),
        ),
        migrations.AddField(
            model_name='bill',
            name='small_changes',
            field=models.SmallIntegerField(default=40, verbose_name='ilość małych zmian'),
        ),
    ]
