# Generated by Django 2.1.2 on 2018-10-26 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_auto_20181026_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data'),
        ),
    ]
