# Generated by Django 2.1.2 on 2018-10-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_auto_20181026_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='big_changes',
            field=models.SmallIntegerField(default=20, verbose_name='ilość dużych zmian'),
        ),
    ]
